name: Postgres Compiler Check

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - run: cat /etc/os-release
    - run: sudo apt-get update
    - run: sudo apt-get upgrade
    - run: apt-cache show postgresql-server-dev-14
    - run: sudo apt-get install postgresql-server-dev-14
    - run: cat /usr/lib/postgresql/14/lib/pgxs/src/Makefile.global | grep -E ^CLANG
    - run: cat /etc/apt/sources.list | grep -E ^deb
